ropensci/openalexR

- DESCRIPTION
- vignettes/articles/About-the-tibble-output.Rmd
> A vignette to wrangle tibble output

- R/oa2df.R
- R/oa_fetch.R
- R/oa_snowball.R
- man/oa_fetch.Rd
- man/oa_snowball.Rd
- tests/testthat/test-oa_snowball.R
- tests/testthat/test-utils.R
> Refine snowball

- R/oa2df.R
closes https://github.com/massimoaria/openalexR/issues/27
I ran R CMD check without issues -- let me know if you want any test or the like, but didn't seem particularly necessary for just adding columns.
> Add is_paratext & is_retracted as columns in work2df

- R/oa2df.R
> rbind.data.frame needs same names

- _pkgdown.yml
> Group functions in Reference

- DESCRIPTION
- NEWS.md
- R/oa_fetch.R
- R/utils.R
- README.Rmd
- README.md
- man/oa_fetch.Rd
- man/oa_query.Rd
- man/oa_request.Rd
Allow the user to supply their API key if they have OpenAlex Premium. 
https://openalex.org/pricing
> api_key as a new argument to oa_fetch

- R/oa2bibliometrix.R
- R/oa2df.R
- man/oa2bibliometrix.Rd
- man/works2df.Rd
- tests/testthat/test-oa2bibliometrix.R
Addresses https://github.com/ropensci/openalexR/issues/38#issuecomment-1557466103
> Safe rbind for works2df

- NEWS.md
- R/oa_fetch.R
- man/oa_request.Rd
- tests/testthat/test-oa_fetch.R
I implemented basic paging for when `options$sample` is specified. (Details in #106).
> basic paging, closes #106

- DESCRIPTION
- R/oa2bibliometrix.R
- R/openalexR-internal.R
> Add onAttach message

- vignettes/articles/A_Brief_Introduction_to_openalexR.Rmd
Hot fix for https://github.com/r-universe/ropensci/actions/runs/5679193215/job/15390913797
https://github.com/ropensci/openalexR/issues/138#issuecomment-1653460050
> Author ids new rollout

- tests/testthat/test-oa_fetch.R
Addresses https://github.com/ropensci/openalexR/issues/138#issuecomment-1667599059
> Less stringent tests

- R/oa_ngrams.R
- man/oa_ngrams.Rd
Address Reviewer 1's feedback.
> remove dplyr in example

- R/oa2df.R
- R/oa_fetch.R
- man/oa_fetch.Rd
- man/oa_query.Rd
> Fix works2df when there are multiple institution lineages 

- R/oa2df.R
- R/oa_fetch.R
- man/oa2df.Rd
- tests/testthat/test-oa_fetch.R
> Fix options when oa_request returns only one entry

- NEWS.md
- R/oa_fetch.R
- man/oa_request.Rd
- tests/testthat/test-oa_fetch.R
> Allow specifying sample when using search

- R/oa_ngrams.R
- vignettes/articles/A_Brief_Introduction_to_openalexR.Rmd
A proposal to resolve check errors on CRAN when OA does not respond for some reason.
> A proposal to resolve check errors on CRAN when OA does not respond for some reason.

- R/oa2df.R
- R/oa_fetch.R
- R/oa_ngrams.R
- man/authors2df.Rd
- man/concepts2df.Rd
- man/funders2df.Rd
- man/institutions2df.Rd
- man/publishers2df.Rd
- man/sources2df.Rd
- man/venues2df.Rd
- man/works2df.Rd
- tests/testthat/test-oa2df.R
- tests/testthat/test-oa_fetch.R
- tests/testthat/test-oa_ngrams.R
Looks like I forgot to skip some tests on CRAN. This PR should fix this issue.
https://cran.r-project.org/web/checks/check_results_openalexR.html
> Skip making API queries on CRAN

- R/oa2df.R
- tests/testthat/test-oa_fetch.R
Resolves #196
`oa_fetch()` for authors now also includes `affiliations_other`, a list-column of institution IDs for the author's other affiliations.
``` r
author <- oa_fetch("author", "https://openalex.org/A5019422724")
author[, c("affiliations_other")]
#> # A tibble: 1 × 1
#>   affiliations_other
#>   <list>            
#> 1 <chr [4]>
author$affiliations_other
#> [[1]]
#> [1] "https://openalex.org/I138006243"  "https://openalex.org/I4210124125"
#> [3] "https://openalex.org/I4210166612" "https://openalex.org/I179638627"
```
More information about the other affiliations can simply be retrieved through a separate query
```r
oa_fetch("institution", author$affiliations_other[[1]]) |>
dplyr::glimpse()
#> Rows: 4
#> Columns: 21
#> $ id                         <chr> …
```
> New authors2df column for other/previous affiliations

- R/oa_fetch.R
Not the most graceful way to resolve #204 but I think this happens very rarely, so allowing the user to set their own `per_page` argument makes sense to me.
> Accounts for 503 Error

- R/oa2df.R
- tests/testthat/test-oa_fetch.R
Resolves #213
```r
x <- oa_fetch(identifier = c("W1964141474", "W2741809807"))
x[, "topics"]
#> # A tibble: 2 × 1
#>   topics           
#>   <list>           
#> 1 <tibble [12 × 5]>
#> 2 <tibble [12 × 5]>
x$topics
#> [[1]]
#> # A tibble: 12 × 5
#>        i score name     id                                  display_name                             
#>    <int> <dbl> <chr>    <chr>                               <chr>                                    
#>  1     1 0.997 topic    https://openalex.org/T10102         Bibliometric Analysis and Research Evalu…
#>  2     1 0.997 subfield https://openalex.org/subfields/1804 Statistics, Probability and Uncertainty  
#>  3     1 0.997 field    https://openalex.org/fields/18      Decision Sciences                        
#>  4     1 0.997 domain …
```
> add Work `topics` field

- R/oa_fetch.R
> Handle large request errors

- R/oa2df.R
- tests/testthat/test-oa_fetch.R
Closes #240.
``` r
openalexR::oa_fetch(identifier = "W1650596822") |>
tidyr::unnest(author) |> 
dplyr::select(au_affiliation_raw)
#> # A tibble: 2 × 1
#>   au_affiliation_raw                                                            
#>   <chr>                                                                         
#> 1 Clinic of Gastroenterology and Rheumatology, Division of Hepatology, Leipzig …
#> 2 Clinic of Gastroenterology and Rheumatology, Division of Hepatology, Leipzig …
```
<sup>Created on 2024-05-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Fixes au_affiliation_raw

- R/oa_snowball.R
- tests/testthat/test-oa_snowball.R
> Handles NULL edges in oa_snowball

- R/oa2bibliometrix.R
- R/openalexR-coverage.R
> use getExportedValue() to get LazyData

- R/oa2df.R
Will keep this as draft for a bit in case other issues arise as we play around with it more in prep for #284 
The mangling in question:
> Minor fixes for `snowball2df()`

- tests/testthat/test-oa_fetch.R
> use a slightly different query in test
