ropensci/openalexR

- R/oa_snowball.R
- man/oa_snowball.Rd
- tests/testthat/test-oa_snowball.R
`oa_snowball` no longer errors out when a work hasn't been cited.
``` r
snowball_docs <- oa_snowball(
identifier = c("W4295757800", "W4296128995", "W4297497355"),
endpoint = "https://api.openalex.org/",
verbose = FALSE
)
#> the list does not contain a valid OpenAlex collection
head(snowball_docs)
#> # A tibble: 6 × 27
#>   id        displ…¹ author ab    publi…² relev…³ so    so_id publi…⁴ issn  url  
#>   <chr>     <chr>   <list> <chr> <chr>   <lgl>   <chr> <chr> <chr>   <lis> <chr>
#> 1 https://… Deep R… <df>   Deep… 2016-0… NA      2016… <NA>  IEEE    <lgl> http…
#> 2 https://… SWISS-… <df>   Homo… 2018-0… NA      Nucl… http… Oxford… <chr> http…
#> 3 https://… Molecu… <df>   Oral… 2002-0… NA      Jour… http… Americ… <chr> http…
#> 4 https://… Highly… <df>   Prot… …
```
> Fix snowball

- R/oa_snowball.R
- man/to_disk.Rd
- tests/testthat/test-oa_snowball.R
addresses #23
``` r
flat_snow <- to_disk(oa_snowball(
identifier = "W1516819724",
verbose = TRUE
))
#> Requesting url: https://api.openalex.org/works/W1516819724
#> Collecting all documents citing the target papers...
#> Requesting url: https://api.openalex.org/works?filter=cites%3AW1516819724
#> About to get a total of 1 pages of results with a total of 4 records.
#> Collecting all documents cited by the target papers...
#> Requesting url: https://api.openalex.org/works?filter=cited_by%3AW1516819724
#> One list does not contain a valid OpenAlex collection
flat_snow[, c("id", "connection", "connection_count")]
#>            id                                      connection connection_count
#> 1 W1516819724 W2613880959;W2579547421;W2251756894;W3045921891 …
```
> Slightly modify to_disk

- R/oa2df.R
Closes #36.
I pinpointed it to W4206756298 where the `authorships$author` field is an empty named list.
``` r
oa_fetch("W4206756298")
#> # A tibble: 1 × 28
#>   id        displ…¹ author ab    publi…² relev…³ so    so_id publi…⁴ issn  url  
#>   <chr>     <chr>   <list> <lgl> <chr>   <lgl>   <chr> <chr> <chr>   <lis> <chr>
#> 1 https://… Transm… <df>   NA    1997-0… NA      The … http… New En… <chr> http…
#> # … with 17 more variables: first_page <chr>, last_page <chr>, volume <chr>,
#> #   issue <chr>, is_oa <lgl>, cited_by_count <int>, counts_by_year <list>,
#> #   publication_year <int>, cited_by_api_url <chr>, ids <list>, doi <chr>,
#> #   type <chr>, referenced_works <list>, related_works <list>,
#> #   is_paratext <lgl>, is_retracted <lgl>, concepts <list>, and …
```
> Handle empty author

- R/oa_snowball.R
Just wraps `$edges` in `na.omit()` before returning from `oa_snowball()`.
```r
devtools::load_all()
set <- c("W1992473459", "W4246185059", "W3119850932")
snowballed <- oa_snowball(set) # finds ~200 papers
anyNA(snowballed$edges)
```
> na.omit to fix #51

- R/oa2df.R
Adds a step after the conversion of `$concepts` from list to df, to ensure that missingness is encoded as `NULL` (#56) and the `score` column is double when it exists (#57).
```r
papers <- oa_fetch(c("W2755950973", "W4296015844"), "works")
papers$concepts
#> [[1]]
#>                                 id                               wikidata     display_name level     score
#> 1   https://openalex.org/C41008148   https://www.wikidata.org/wiki/Q21198 Computer science     0 0.6361582
#> 2 https://openalex.org/C2522767166 https://www.wikidata.org/wiki/Q2374463     Data science     1 0.3629617
#> 
#> [[2]]
#> NULL
typeof( papers$concepts[[1]]$score )
#> [1] "double"
```
> Type handling for the `concepts` list-column of `"works"` entity

- R/oa_ngrams.R
- README.Rmd
- man/oa_ngrams.Rd
The [new curl release today](https://ropensci.org/blog/2023/01/13/curl5-release/) adds the parallelized `multi_download()` function, which we can use to significantly speed up `oa_ngrams()` which currently requests/parses one-by-one (we can't do a batch request like in `oa_fetch()` because the ngrams API is async and static).
I'm leaving this as a draft until we decide whether we should:
1) Import `curl` >=5.0.0, OR
2) Import `curl` without version spec as we do currently, but use `multi_download()` if pkg version is >=5.0.0
Until we resolve that, the newer/faster version is added to this draft PR as `oa_ngrams2()`:
```r
devtools::load_all()
single <- "W1963991285"
system.time(ngram_single1 <- oa_ngrams(single))
#> user  system elapsed 
#> 0.02    0.01    0.18 
#> …
```
> `oa_ngrams` speed up with new `{curl}` v5.0.0

- R/oa2df.R
- R/utils.R
Previously, `do.call(rbind, ...)` errors out when the list elements don't have the same names. The new function `rbind_oa_ls` allows rbind to work and set unavailable names to NA, so this now works:
``` r
openalexR::oa_fetch("authors", display_name.search = "Trang T Le")
```
> safe rbind in oa2df

- R/oa_ngrams.R
- cran-comments.md
Hi team -
Yesterday I received a CRAN email asking us to use string for comparing package versions for one of my own packages, and saw openalexR on the list as well. I realized that I was responsible for this in how I wrote `oa_ngrams()` - apologies!
This is a small PR to use `"5"` instead of `5` when checking for `{curl}` version. So it's now:
```
utils::packageVersion("curl") >= "5"
```
I also added a comment for CRAN telling them that we fixed it.
Thanks!
> CRAN patch request to use string for comparing package versions

- R/oa2df.R
- R/oa_fetch.R
- R/oa_snowball.R
- R/utils.R
- README.md
- man/oa_snowball.Rd
- tests/testthat/test-oa_fetch.R
- vignettes/articles/About-the-tibble-output.Rmd
> Open access

- R/oa2df.R
Before this fix, we get an error because the 2nd element of [`final_res`](https://github.com/ropensci/openalexR/blob/71b8715687ab9c9e28f3fe6ab99e05ea01f3f26d/R/oa_fetch.R#L141) in the below computation is an empty list since the 2nd element of [`list_id`](https://github.com/ropensci/openalexR/blob/71b8715687ab9c9e28f3fe6ab99e05ea01f3f26d/R/oa_fetch.R#L104C23-L104C30) contains the last 2 works with no citations yet (W4301494992 and W87230806). 
``` r
my_papers <- c("W2741809807", "W2122130843", "W2041540760", "W2038196424", "W2396414759", "W2059275568", "W3130540911", "W2104791248", "W1553564559", "W2051771537", "W2144816075", "W2980172586", "W1519117689", "W4235038322", "W2014140050", "W2109312864", "W4229010617", "W4245410681", "W2143461694", "W2949258821", …
```
> Account for empty element in final_res

- R/oa_fetch.R
- R/oa_snowball.R
- man/oa_fetch.Rd
- man/oa_request.Rd
- tests/testthat/test-oa_fetch.R
Resolves #166.
Hi @rkrug, could you try installing this branch and see if this works for your use case in #166?
``` r
remotes::install_github("ropensci/openalexR@generalize-paging")
```
For example, what you can now do is specifying the pages:
``` r
chunk_size <- 5
for (i in 1:3){
start <- chunk_size*(i-1) + 1
end <- chunk_size*i
oa_fetch(
search = "transformative change", 
pages = start:end,
per_page = 20,
verbose = TRUE
) |>
saveRDS(file = sprintf("tfc-nature_p%s-%s.rds", start, end))
}
```
One thing I'd like to note is that concatenating these `rds` files later may still raise memory issues if you're trying to do this in R. I recommend checking out [`arrow::write_parquet`](https://arrow.apache.org/docs/r/reference/write_parquet.html) to save these outputs as parquet files which would …
> improve paging control

- vignettes/articles/Filters.Rmd
- vignettes/articles/institution.Rmd
Looks like the doc build fails because of the deprecated usage of the "venues" entity in Filters.Rmd. This PR fixes this vignette.
> Resolves #187

- R/oa_fetch.R
Fixes #200 
`oa_query()` now errors if it receives a filter with a missing value, instead of silently ignoring it. Guards against users accidentally specifying a filter that ends up not doing anything.
```r
author_id <- NULL
author_works <- oa_fetch(
entity = "works",
author.id = author_id,
publication_year = 2022,
verbose = TRUE
)
#> Error: Filters must have a value: author.id
```
> empty filter check

- R/oa_fetch.R
- man/oa_query.Rd
- man/oa_request.Rd
> update oa_query and oa_request examples

- R/oa2df.R
Closes #205 
``` r
author_works <- oa_fetch(
entity = "works",
author.id = "a5016874418",
publication_year = 2023,
verbose = TRUE
)
#> Requesting url: https://api.openalex.org/works?filter=author.id%3Aa5016874418%2Cpublication_year%3A2023
#> Getting 1 page of results with a total of 9 records...
tail(author_works[[3]][[1]][,1:5])
#>                              au_id    au_display_name
#> 1 https://openalex.org/A5045990380  Mohanad Al-Obaidi
#> 2 https://openalex.org/A5011527972    Ahmet B. Gungor
#> 3 https://openalex.org/A5070604106      Sandra Kurtin
#> 4 https://openalex.org/A5027594045     Ann E. Mathias
#> 5 https://openalex.org/A5016874418    Bekir Tanrıöver
#> 6 https://openalex.org/A5076993071 Tirdad T. Zangeneh
#>                                au_orcid …
```
> Add is_corresponding

- R/oa2df.R
- tests/testthat/test-oa_fetch.R
I went ahead and include `title` as a new column in concordance with how OpenAlex keeps both "title" and "display_name".
Closes #218.
> Add title for works

- R/oa_snowball.R
- man/oa_snowball.Rd
- man/openalexR-package.Rd
Ref: #259
(the package .Rd file got updated from running `document()` and reflects work of a prev PR)
> Show search by DOI in `oa_snowball()` examples

- R/oa2df.R
The `as.Date()` conversion of the `publication_date` gets the job done but is clunky and applied very narrowly.
I went through the API docs and there are only the two other places where the API returns date values: `updated_date` and `created_date`. These are OpenAlex-specific metadata and `oa2df()` sometimes returns them depending on the entity. I have less thoughts on these guys.
Date values aren't automatically converted by the JSON parser, like how integer/double/logical/etc. are - not sure if we want a bigger discussion around that (but perhaps at least not at this stage, given how rare date fields are?)
> Parse Works objects `publication_date` field as date type

- R/oa_fetch.R
In `oa_fetch()`, there's a clause to return `res` (the single initial query we do at the start to compute on metadata for stuff like # of pages to expect) early when the `meta` field is empty (i.e., simple "direct" queries):
https://github.com/ropensci/openalexR/blob/42f4d1678574f61108dfb5f21c7ad4271c242295/R/oa_fetch.R#L340-L347
At this point of early return, `res` is always the parsed json, so it was not respecting `output = "raw"` in cases like `oa_fetch(identifier = "W4396214724", output = "raw")` which triggers that early return. 
The PR makes it so that this initial `res` can stay either parsed or unparsed, so that it can be returned unparsed if user specifies `output = "raw"`. Since we do need the parsed metadata info, that's now tracked in `res_meta`. The roundabout way of doing …
> Respect `output = "raw"` in `oa_fetch()` when result is returned early

- R/oa2df.R
Closes #305. 
``` r
paper <- oa_fetch(identifier = "W2101805856", output = "list")
paper$apc_list
#> $value
#> [1] 3500000
#> 
#> $currency
#> [1] "IRR"
#> 
#> $value_usd
#> NULL
#> 
#> $provenance
#> [1] "doaj"
if (any(lengths(paper[c("apc_list", "apc_paid")]) > 0)) {
apc_fields <- list(value = NA, currency = NA, value_usd = NA, provenance = NA)
apc <- list(rbind.data.frame(list(
c(type = "list", utils::modifyList(apc_fields, as.list(paper$apc_list))),
c(type = "paid", utils::modifyList(apc_fields, as.list(paper$apc_paid)))
)))
}
#> Error in rbind.data.frame(list(c(type = "list", utils::modifyList(apc_fields, : invalid list argument: all variables should have the same length
if (any(lengths(paper[c("apc_list", "apc_paid")]) > 0)) {
apc_fields <- list(value = NA, …
```
> fix apc processing for W2101805856

- R/oa_fetch.R
- tests/testthat/test-group_by.R
- tests/testthat/test-oa_fetch.R
During paging, we can't add `cursor=*` to the [URL](
https://api.openalex.org/works?search=biodiversity&group_by=is_oa&cursor=*) because 
> Cannot use cursor pagination when grouping fields that return true or false.
We now limit pagination to only when there are more groups than `per_page`.
> Fix group_by for boolean groups
